# Generated by Django 5.1.3 on 2026-05-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_cpc"),
    ]

    operations = [
        migrations.CreateModel(
            name="IEA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.TextField()),
                ("section_title", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
