# Generated by Django 6.0.5 on 2026-05-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_iea"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caseHeading", models.TextField()),
                ("applicableArticle", models.TextField()),
                ("tags", models.TextField()),
                ("query", models.TextField()),
                ("status", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("act_name", models.TextField()),
                ("description", models.TextField()),
                ("pdf", models.BinaryField()),
            ],
        ),
    ]
