# Generated by Django 6.0.5 on 2026-05-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_case_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="BNSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.TextField()),
                ("section_title", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BSA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.TextField()),
                ("section_title", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
