# Generated by Django 6.0.5 on 2026-05-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_bnss_bsa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bns",
            options={"verbose_name": "BNS", "verbose_name_plural": "BNS"},
        ),
        migrations.AlterModelOptions(
            name="bnss",
            options={"verbose_name": "BNSS", "verbose_name_plural": "BNSS"},
        ),
        migrations.AlterModelOptions(
            name="bsa",
            options={"verbose_name": "BSA", "verbose_name_plural": "BSA"},
        ),
        migrations.AlterModelOptions(
            name="case",
            options={"verbose_name": "Case", "verbose_name_plural": "Cases"},
        ),
        migrations.AlterModelOptions(
            name="cpc",
            options={"verbose_name": "CPC", "verbose_name_plural": "CPC"},
        ),
        migrations.AlterModelOptions(
            name="crpc",
            options={"verbose_name": "CrPC", "verbose_name_plural": "CrPC"},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterModelOptions(
            name="iea",
            options={"verbose_name": "IEA", "verbose_name_plural": "IEA"},
        ),
        migrations.AlterModelOptions(
            name="ipc",
            options={"verbose_name": "IPC", "verbose_name_plural": "IPC"},
        ),
        migrations.AlterModelOptions(
            name="mva",
            options={"verbose_name": "MVA", "verbose_name_plural": "MVA"},
        ),
        migrations.AlterModelOptions(
            name="query",
            options={"verbose_name": "Query", "verbose_name_plural": "Queries"},
        ),
    ]
