# Generated by Django 6.0.5 on 2026-05-21 05:38

import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_bns_options_alter_bnss_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={},
        ),
        migrations.RemoveField(
            model_name="document",
            name="act_name",
        ),
        migrations.RemoveField(
            model_name="document",
            name="description",
        ),
        migrations.RemoveField(
            model_name="document",
            name="pdf",
        ),
        migrations.RemoveField(
            model_name="query",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="bns",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bns",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="bns_pdfs/"),
        ),
        migrations.AddField(
            model_name="bnss",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bnss",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="bnss_pdfs/"),
        ),
        migrations.AddField(
            model_name="bsa",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bsa",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="bsa_pdfs/"),
        ),
        migrations.AddField(
            model_name="cpc",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cpc",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="cpc_pdfs/"),
        ),
        migrations.AddField(
            model_name="crpc",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="crpc",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="crpc_pdfs/"),
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(default="Untitled Document", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iea",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iea",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="iea_pdfs/"),
        ),
        migrations.AddField(
            model_name="ipc",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ipc",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="ipc_pdfs/"),
        ),
        migrations.AddField(
            model_name="mva",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mva",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="mva_pdfs/"),
        ),
        migrations.AddField(
            model_name="query",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="bns",
            name="description",
            field=models.TextField(
                help_text="Maximum 50 words only",
                validators=[home.models.validate_50_words],
            ),
        ),
        migrations.AlterField(
            model_name="bns",
            name="section_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="bns",
            name="section_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="bnss",
            name="description",
            field=models.TextField(
                help_text="Maximum 50 words only",
                validators=[home.models.validate_50_words],
            ),
        ),
        migrations.AlterField(
            model_name="bnss",
            name="section_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="bnss",
            name="section_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="bsa",
            name="description",
            field=models.TextField(
                help_text="Maximum 50 words only",
                validators=[home.models.validate_50_words],
            ),
        ),
        migrations.AlterField(
            model_name="bsa",
            name="section_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="bsa",
            name="section_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="case",
            name="applicableArticle",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="case",
            name="caseHeading",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cpc",
            name="description",
            field=models.TextField(
                help_text="Maximum 50 words only",
                validators=[home.models.validate_50_words],
            ),
        ),
        migrations.AlterField(
            model_name="cpc",
            name="section_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cpc",
            name="section_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="crpc",
            name="description",
            field=models.TextField(
                help_text="Maximum 50 words only",
                validators=[home.models.validate_50_words],
            ),
        ),
        migrations.AlterField(
            model_name="crpc",
            name="section_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="crpc",
            name="section_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="iea",
            name="description",
            field=models.TextField(
                help_text="Maximum 50 words only",
                validators=[home.models.validate_50_words],
            ),
        ),
        migrations.AlterField(
            model_name="iea",
            name="section_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="iea",
            name="section_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="ipc",
            name="description",
            field=models.TextField(
                help_text="Maximum 50 words only",
                validators=[home.models.validate_50_words],
            ),
        ),
        migrations.AlterField(
            model_name="ipc",
            name="section_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="ipc",
            name="section_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="mva",
            name="description",
            field=models.TextField(
                help_text="Maximum 50 words only",
                validators=[home.models.validate_50_words],
            ),
        ),
        migrations.AlterField(
            model_name="mva",
            name="section_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="mva",
            name="section_title",
            field=models.CharField(max_length=300),
        ),
    ]
